### ISSUE TITLE
Server-side compatibility 

### ISSUE THREAD

**Issue by leesiongchan** [wikibus/heracles#15]
I see this library relies on `window.fetch`, do you think we could safely switch to `isomorphic-fetch` to have the full support of server-side?

**Comment by tpluscode** [comment]
I was considering `isomorphic-fetch` at some point but I was worried that I would force it even into browsers which support `fetch` natively. 

How can I avoid that and make it load only in browsers which don't have it natively?

**Comment by leesiongchan** [comment]
`isomorphic-fetch` uses `whatwg-fetch` behind the scene and `whatwg-fetch` will not load when it detects the browsers have already support natively.

Here is the note
https://github.com/github/fetch#browser-support
`
Note: modern browsers such as Chrome, Firefox, Microsoft Edge, and Safari contain native implementations of window.fetch, therefore the code from this polyfill doesn't have any effect on those browsers. If you believe you've encountered an error with how window.fetch is implemented in any of these browsers, you should file an issue with that browser vendor instead of this project.
`

**Comment by tpluscode** [comment]
Switched to webpack and `isomorphic-fetch`. Closing.
